service:
  name: Random Rewards
  description: Random Rewards
  version: 0.0.1
  api:
    baseUrl: /api
  docs:
    baseUrl: /docs
    username: username
    password: password

server:
  host: localhost
  port: 3000
